service: ${file(./package.json):name}

custom: ${file(./config.js):buckets}

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:custom.producerBucket}
            - "/*"
functions:
  produce:
    handler: handlers/producer.produce
    events:
      - schedule: rate(1 hour)
    environment:
      TZ: Europe/Belfast
      EVENTBRITE_API_TOKEN: ${ssm:eventbriteApiToken~true}

resources:
  Resources:
    S3BucketMuxerProducedEventsEventbrite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.producerBucket}
